### ISSUE TITLE
Dopolnitve

### ISSUE THREAD

**Issue by RobertIlovar** [vevrca-web/vevrca#10]
Preko Wetransfer pošiljam paket, ki vsebuje naslednje dopolnitve:

**1. Uvodna stran**
- še enkrat pošiljam tri fotografije za uvodni sklop (okrogle),
- nova fotka "kdo smo",
- nova fotka Klemen,
- nova slika sveta, v psd, ločen svet in oznake.

**2. Varnost**
- popravljena razdelka "Varnost" in "Parki". Presledki med odstavki so dvojni, prav tako odmiki od robov razdelkov (prikaz odmikov v psd z rumenim modulom a). Fotografije se tako lahko pozicionirajo primerno ob tekst. 

Parki -> Podkategoriji "Izgradnja" sta v enaki velikosti, kot body tekst, le da sta bold.

**3. Zip-line**
- nova naslovna slika
- nova slika skakalca

**4. Ostale stroritve**
- nove fotografije, poimenovane po pozicijah.

**5. Dodatno**
- Pri glavnem meniju bi prosil za podčrtavanje z debelejšo linijo, tako kot na sliki.
  <img width="525" alt="screen shot 2016-05-26 at 11 21 20" src="https://cloud.githubusercontent.com/assets/18597636/15572028/9301d060-233e-11e6-8b0a-a071e33a8248.png">
- Pri mobilcih in tablicah bi prosil, da se ikona "Meni" nadomesti s hamburgerjem (tri horizontale), tako kot v predlogu.
  ![vevrca_web_mobile](https://cloud.githubusercontent.com/assets/18597636/15572056/b42fd912-233e-11e6-8960-4b29ec855b1d.jpg)
- Pri Adrenalinskih parkih in pri Zip-line bi prosil za enakomerne odmike besedila od fotografij, zgoraj in spodaj, tako kot na sliki.
  <img width="1059" alt="screen shot 2016-05-26 at 11 24 11" src="https://cloud.githubusercontent.com/assets/18597636/15572064/b8db4e38-233e-11e6-954b-dfe16a59a8df.png">

**Comment by HriBB** [comment]
**1. Uvodna stran**
- [x] še enkrat pošiljam tri fotografije za uvodni sklop (okrogle),
- [x] nova fotka "kdo smo",
- [x] nova fotka Klemen,
- [x] nova slika sveta, v psd, ločen svet in oznake.

**2. Varnost**
- [x] popravljena razdelka "Varnost" in "Parki". Presledki med odstavki so dvojni, prav tako odmiki od robov razdelkov (prikaz odmikov v psd z rumenim modulom a). Fotografije se tako lahko pozicionirajo primerno ob tekst.
- [x] Parki -> Podkategoriji "Izgradnja" sta v enaki velikosti, kot body tekst, le da sta bold.

**3. Zip-line**
- [x] nova naslovna slika
- [x] nova slika skakalca

**4. Ostale stroritve**
- [x] nove fotografije, poimenovane po pozicijah.

**5. Dodatno**
- [x] Pri glavnem meniju bi prosil za podčrtavanje debelejšo linijo
- [x] Pri mobilcih in tablicah bi prosil, da se ikona "Meni" nadomesti s hamburgerjem
- [x] Pri Adrenalinskih parkih in pri Zip-line bi prosil za enakomerne odmike besedila od fotografij
