### ISSUE TITLE
Logo v sekciji varnost naj bo svg

### ISSUE THREAD

**Issue by HriBB** [vevrca-web/vevrca#3]

**Comment by RobertIlovar** [comment]
[Logo.zip](https://github.com/vevrca-si/website/files/230157/Logo.zip)

**Comment by RobertIlovar** [comment]
[Certifikati.zip](https://github.com/vevrca-si/website/files/230161/Certifikati.zip)
Tole so oznake, Vertic Alps žal nimam v višji resoluciji, mogoče ga lahko dobi Tine?

**Comment by HriBB** [comment]
@RobertIlovar a mi lahko pošlješ prosim še navaden logo v svg obliki, ta ki je na prvi strani v sekciji "Zagotavljamo popolno varnost"

**Comment by RobertIlovar** [comment]
[Znaka.zip](https://github.com/vevrca-si/website/files/279543/Znaka.zip)
