### ISSUE TITLE
Pregled 21.4.

### ISSUE THREAD

**Issue by RobertIlovar** [vevrca-web/vevrca#6]
Splošno
- pri zelo širokem zaslonu je znak Vevrca in naslov zamaknjen levo glede na podatkovni del. Ali je možno, da se poravnata?

Meni
- bolj razpotegnejen čez širino, tako kot v predlogi
- oznaki jezika - dvigniti tekst SL/EN toliko, da bo sredinsko glede na krog

Footer
- pri podatkih zmanjšati medvrstični razmak, da bo tako kot v predlogi

Landing page
- naslovna slika višja - kot v predlogi
- krožne slike manjše - kot v predlogi
- odmik “Kdo smo” naslova od roba naj bo enak, kot v predlogi
- fotka pri “Kdo smo” naj bo duotone, kot v predlogi
- odmik teksta od roba naj bo manjši 

Adrenalinski parki
zmanjšati odmike teksta od modulov, sicer odlično

Zip-line parki
- tri slike - pri ožanju zaslona slike skočijo iz treh v vrsti v eno v vrsti. Prosil bi še za en korak, kjer se tretja zloži pod zgornji dve.

Ostale storitve
- zmanjšati odmike teksta od zgornjega in spodnjega roba podatkovnega modula.

Reference
- povečati odmik modulov od footerja

**Comment by HriBB** [comment]
Super! Bom popravil.

**Comment by HriBB** [comment]
Splošno
- [x] pri zelo širokem zaslonu je znak Vevrca in naslov zamaknjen levo glede na podatkovni del. Ali je možno, da se poravnata?

Meni
- [x] bolj razpotegnejen čez širino, tako kot v predlogi
- [x] oznaki jezika - dvigniti tekst SL/EN toliko, da bo sredinsko glede na krog

Footer
- [x] pri podatkih zmanjšati medvrstični razmak, da bo tako kot v predlogi

Landing page
- [x] naslovna slika višja - kot v predlogi
- [x] krožne slike manjše - kot v predlogi
- [x] odmik “Kdo smo” naslova od roba naj bo enak, kot v predlogi
- [x] fotka pri “Kdo smo” naj bo duotone, kot v predlogi
- [x] odmik teksta od roba naj bo manjši

Adrenalinski parki
- [x] zmanjšati odmike teksta od modulov, sicer odlično

Zip-line parki
- [x] tri slike - pri ožanju zaslona slike skočijo iz treh v vrsti v eno v vrsti. Prosil bi še za en korak, kjer se tretja zloži pod zgornji dve.

Ostale storitve
- [x] zmanjšati odmike teksta od zgornjega in spodnjega roba podatkovnega modula.

Reference
- [x] povečati odmik modulov od footerja

Super, hvala! Samo še dve stvari:
- [x] naslovne slike - na landing page-u ustrezna višina, drugje so previsoke. V predlogi predvideno, da so naslovne slike na notranjih straneh nižje.
- [ ] znak Vevrca ima drugačno modro, kot je v predlogi in v ozadju prvega mudula na landing page-u. Prilagam še enkrat psd. Vevrca_znak_Smart_object.zip

**Comment by RobertIlovar** [comment]
Super, hvala! Samo še dve stvari:
- naslovne slike - na landing page-u ustrezna višina, drugje so previsoke. V predlogi predvideno, da so naslovne slike na notranjih straneh nižje.
- znak Vevrca ima drugačno modro, kot je v predlogi in v ozadju prvega mudula na landing page-u. Prilagam še enkrat psd.
  [Vevrca_znak_Smart_object.zip](https://github.com/vevrca-si/website/files/279559/Vevrca_znak_Smart_object.zip)

**Comment by HriBB** [comment]
@RobertIlovar a mi lahko prosim pošlješ svg, ker men ni jasno kako exportat smart object v svg s photoshopom. Illustratorja pa nimam

**Comment by HriBB** [comment]
Popravil sem
- [x] pri zelo širokem zaslonu je znak Vevrca in naslov zamaknjen levo glede na podatkovni del. Ali je možno, da se poravnata?
- [x] fotka pri “Kdo smo” naj bo duotone, kot v predlogi
- [x] odmik teksta od roba naj bo manjši

Prosim še enkrat preveri vse in naredi novo task listo če bo potrebno.
