### ISSUE TITLE
Popravi 404 page

### ISSUE THREAD

**Issue by HriBB** [vevrca-web/vevrca#8]
Cist je bedn

**Comment by RobertIlovar** [comment]
[404.zip](https://github.com/vevrca-si/website/files/279546/404.zip)
Predlog v priponki (jpg), zraven še znak 404 v eps.

**Comment by HriBB** [comment]
@RobertIlovar a to je fullscreen? Zaenkrat sem popravil osnovne wordpress style. Poleg 404 page še search page. Onemogočil sem category, archive in single post view tako da se vedno izvede redirect na home.

**Comment by RobertIlovar** [comment]
Mišljeno je čez cel zaslon, ja. Tudi to, kar je trenutno je ok, le pripraviti je potrebno še sliko za ozadje.

**Comment by HriBB** [comment]
@RobertIlovar ja eno default sliko. Pa pomoje bi bilo za seo kul ce se naredi za vsako referenco standalone page ki ima svoj url. Recimo http://vevrca.si/reference/adrenalinski-park-postojna.

**Comment by RobertIlovar** [comment]
@HriBB Prilagam sliko za 404.
[404.jpg.zip](https://github.com/vevrca-si/website/files/306719/404.jpg.zip)

Se strinjam, da bi bilo dobro za seo, vendar bi bilo slabo za izkušnjo, če bi bila na strani taka količina podatkov, kot jo imamo v karticah. Vsebine bi moralo biti pri vseh projektih toliko, da bi obiskovalec dobil občutek, da je informacija vredna podstrani. Osebno sem proti podstranem, ki so prazne. Kaj predlagaš?

**Comment by HriBB** [comment]
Hmm ja kaj pa vem ... Tako kot je zdej mi je najbl vsec, ker je res simpl in pregledno in tocno ves kje si. Dejstvo pa je da za SEO bi blo fajn met te URLje. Nevem, mogoce bi lahko naredili takole:

/reference
- seznam referenc s sliko
- seznam referenc brez slike

/reference/adrenalinski-park-postojna
- referenca "Adrenalinski park Postojna" z galerijo
- seznam referenc s sliko
- seznam referenc brez slike

Upam da je razumljivo.

**Comment by HriBB** [comment]
BTW: super slika za 404 :)

**Comment by RobertIlovar** [comment]
Pogojno bi šlo, sta pa dve stvari.

Ali bi bila taka podstran dosegljiva samo iz iskalnika, ali bi bila tudi iz seznama? Ker če se pod /reference klikne na kartico in se dobi podstran, ki ni nič drugega kot povečana kartica, zna biti res neprimerno. Obiskovalec to razume kot nateg. 

Podstran z galerijo in podatki bi bila še mogoča, podstran brez njih pa zares čudna. Prilagam primer, če prav razumem.

<img width="1011" alt="screen shot 2016-06-09 at 15 58 07" src="https://cloud.githubusercontent.com/assets/18597636/15932340/8f8614d2-2e5b-11e6-8c5a-f5824679f995.png">

404 - tnx :)

**Comment by HriBB** [comment]
@RobertIlovar Ja točno tako sem mislil. Problem je ker wordpress po defaultu omogoča single post page, search page, archive, ... In teh strani ne moremo kar preprosto izklopit.

**404**
http://vevrca.climbuddy.com/asdf

**search results**
http://vevrca.climbuddy.com/?s=park

**single post referenca s slikami**
http://vevrca.climbuddy.com/2016/06/07/adventure-park-jungalooz/

**single post referenca brez slik**
http://vevrca.climbuddy.com/2016/06/18/adventure-park-pine-beach-pakostane-hrvaska/

**category references**
http://vevrca.climbuddy.com/en/category/references/

Zapiram ta issue. Če bo potrebno, odpremo nov issue in tam naprej...
